import { DEFAULT_PAGINATE_OPTIONS, MASTER_JWT_SECRET, NOTEPAD_BUILD_PATH } from './constant';
import { DATABASE, DATABASE_SEED } from './database';

export default () => Object.freeze({
	DATABASE,
	DATABASE_SEED,
	DEFAULT_PAGINATE_OPTIONS,
	MASTER_JWT_SECRET,
	NOTEPAD_BUILD_PATH,
});
