export enum ArithmeticExpressionType {
	$abs = '$abs',
	$add = '$add',
	$ceil = '$ceil',
	$divide = '$divide',
	$exp = '$exp',
	$floor = '$floor',
	$ln = '$ln',
	$log = '$log',
	$log10 = '$log10',
	$mod = '$mod',
	$multiply = '$multiply',
	$pow = '$pow',
	$rand = '$rand',
	$round = '$round',
	$sqrt = '$sqrt',
	$subtract = '$subtract',
	$trunc = '$trunc',
}
