export enum ArrayExpressionType {
	$arrayElemAt = '$arrayElemAt',
	$arrayToObject = '$arrayToObject',
	$concatArrays = '$concatArrays',
	$every = '$every',
	$filter = '$filter',
	$indexOfArray = '$indexOfArray',
	$isArray = '$isArray',
	$map = '$map',
	$none = '$none',
	$objectToArray = '$objectToArray',
	$range = '$range',
	$reduce = '$reduce',
	$reverseArray = '$reverseArray',
	$size = '$size',
	$slice = '$slice',
	$some = '$some',
}
